### PR TITLE
EP-1594: Remove mobile-footer-persist

### PR DESCRIPTION
**Pull request by OzzieOrca**
@riceguitar or @j2trumpet Can you guys resolve the alignment and spacing issues now that the table footer is show inline? I could spend a while trying to figure out what the correct paddings should be and figuring out how they are supposed to be aligned but I'm sure you guys have a better idea of what you want. Seems like the text should be right aligned with the other lines but I'm not sure if the whole thing should be centered on mobile or not. Looks like someone tried to add some custom overrides for xs devices to make it centered and remove the spacing but I'm not sure they are needed anymore.

screen shot 2016-12-12 at 2 53 10 pm
screen shot 2016-12-12 at 2 51 55 pm
screen shot 2016-12-12 at 2 51 28 pm

### CODE REVIEW

**Comment by adammeyer** [comment]
@OzzieOrca Can you review @j2trumpet commit?

**Comment by j2trumpet** [comment]
@OzzieOrca HTML/CSS changes look good to me.

**Comment by OzzieOrca** [comment]
This seems to still have a spacing issue:
screen shot 2016-12-16 at 12 22 13 pm

**Comment by adammeyer** [comment]
@OzzieOrca Was that issue fixed?  I noticed the PR was merged.

**Comment by OzzieOrca** [comment]
Ya. John and I had talked about it. I should have commented here. It no longer has that issue.

**Comment by adammeyer** [comment]
👍

**Pull request merged**
