### PR TITLE
Set up global websites modal

### PR DESCRIPTION
**Pull request by OzzieOrca**
You can put `ng-click="$ctrl.dismiss()"` on any element you want to close the modal. You probably need to customize `globalWebsitesModalWindow.tpl.html` to get the modal styles you need. Let me know if you run into any issues.

### CODE REVIEW

**Comment by adammeyer** [comment]
@OzzieOrca Who was this PR addressed to?

**Comment by OzzieOrca** [comment]
@j2trumpet asked for it

**Comment by adammeyer** [comment]
@j2trumpet Is this good to go?

**Comment by OzzieOrca** [comment]
@adammeyer I don't think he's worked on it yet. I think we was working on the CSS somewhere but it's not in here yet. It needs content.

**Pull request closed without merging**
