### PR TITLE
Analytics fix EP upgrade

### PR DESCRIPTION
**Pull request by wrandall22**
I know you warned me, but I still missed some things in the analytics file.

### CODE REVIEW

**Comment by dr-bizz** [comment]
I'm also seeing that on the branded Checkout we have `.amount` instead of `.AMOUNT`, I guess that needs ti change too?

**Comment by wrandall22** [comment]
No, the `item` and the `config` are not the same objects. I went through branded checkout in the debugger to make sure. It basically ignores the config entirely.

**Comment by dr-bizz** [comment]
I think we might also need to update this page:
`src/common/services/api/designations.service.js` - Line 207 & 217
Screenshot 2023-11-03 at 9 39 15 AM

**Comment by wrandall22** [comment]
`campaign-page` is not in the config per se (e.g. it is not stored in ElasticPath) so the case is correct there. Suggested amounts are managed in AEM. I'll look closer at the amount there, but I think it doesn't need to change.

**Review by dr-bizz — APPROVED** [review]

**Comment by wrandall22** [comment]
Yeah, the suggested amounts piece is correct.

**Pull request merged**
