### PR TITLE
Fix amount handling again

### PR DESCRIPTION
**Pull request by wrandall22**
This is what I should have done instead of #1065.

### CODE REVIEW

**Review by dr-bizz — COMMENTED** [review]
I assume `itemConfigForm.amount` is the `AMOUNT` as as a float?

**Comment by wrandall22** [comment]
No, it is an angular form field which we are adding validators to.

**Comment by dr-bizz** [comment]
This might need to be a seperate PR, but on the `saveGiftToCart()` If you enter an invalid amount, can we show an error?

**Review by dr-bizz — COMMENTED** [review]
This might need to be a separate PR, but on the `saveGiftToCart()` If you enter an invalid amount, can we show an error?

**Comment by wrandall22** [comment]
An invalid amount will be caught by the server and they'll give us back a 400 response, which should be handled nicely in #1067

**Comment by dr-bizz** [comment]
Shoot I missed that PR

**Review by dr-bizz — APPROVED** [review]

**Pull request merged**
