### PR TITLE
changed post URI

### PR DESCRIPTION
**Pull request by EJTison**

### CODE REVIEW

**Comment by wrandall22** [comment]
Treat this `ep-upgrade-stage` branch like the `staging` branch of `ep-commerce`. So make PRs against `ep-upgrade` and just merge into `ep-upgrade-stage`.

**Comment by EJTison** [comment]
Why and how did the commit "[Add ep-upgrade nonprod environments for S3 and Cloudfront](https://github.com/CruGlobal/give-web/pull/985/commits/51da942d0868102f21c864a715c387d3c0a1e798)" get added?

**Comment by wrandall22** [comment]
If your starting branch was `ep-upgrade-stage` rather than `ep-upgrade` it would bring in anything that wasn't in `ep-upgrade` frrom that branch.

**Comment by EJTison** [comment]
Even after rebasing my branch (with 3 commits supposedly) onto ep-upgrade?  I would have thought that was supposed to drop all baggage...

**Comment by wrandall22** [comment]
That brings all `ep-upgrade` commits into your branch, it doesn't bring `ep-upgrade-stage` commits into `ep-upgrade`.

**Comment by EJTison** [comment]
Tested this in staging, and it seems to be working, for whenever you get a chance to review it,  @wrandall22

**Review by wrandall22 — APPROVED** [review]

**Pull request merged**
