### PR TITLE
Strip amount $

### PR DESCRIPTION
**Pull request by wrandall22**
This PR strips out `$` from the gift amount in the product config form.

### CODE REVIEW

**Review by dr-bizz — APPROVED** [review]
JS looks good. I don't see it on stage to test, but I'll approve it for now and test locally

**Comment by wrandall22** [comment]
Can only test on the parallel stage environment at the moment. It is unfortunately still not right due to how `parseFloat` handles commas.

**Comment by dr-bizz** [comment]
I see

**Comment by wrandall22** [comment]
The mix of this and the other branch (better error message) are available to test on https://give-stage2-next.cru.org/

**Review by hlbraddock — APPROVED** [review]

**Pull request merged**
