### PR TITLE
EP-2519 - Add styles for reordering gift selection on useV3.

### PR DESCRIPTION
**Pull request by wjames111**
- move the frequency choice above the amount choice so that the user will pick it first. This should be conditional based on a new configuration option which defaults to the current version.
- Jira [ticket 2517](https://jira.cru.org/browse/EP-2519)

### CODE REVIEW

**Review by dr-bizz — COMMENTED** [review]
The code looks great!

As a personal preference, I think we should remove the padding around the amount if it is no longer the first option. - I also don't know why the padding is there in the first place.

Can we also push this to staging so we can test it there?

Screenshot 2024-11-26 at 9 40 57 AM

**Comment by dr-bizz** [comment]
Ah, since this is going into the `EP-2517-branded-checkout-improvements`, you don't need to add it to staging.

**Comment by wrandall22** [comment]
We won't be able to test in stage until the new config is available in WP or AEM.

**Review by dr-bizz — APPROVED** [review]
Looks great!

**Pull request merged**
