### PR TITLE
Replace json path lib

### PR DESCRIPTION
**Pull request by adammeyer**

### CODE REVIEW

**Comment by adammeyer** [comment]
Sorry for all the commits, I'll squash those.

**Comment by adammeyer** [comment]
This will make the common file so much smaller, yay! 😄  🎉  🎈

**Comment by OzzieOrca** [comment]
Yay 😄

**Comment by OzzieOrca** [comment]
I mean other than killing the coverage by 4% looks good. Maybe I should figure out how to ignore that directory...

**Comment by Omicron7** [comment]
👍 
We should figure out how to ignore any file without coverage. Never see a coverage drop again.

**Pull request merged**
