### PR TITLE
EP-2261: BCO Select Premium

### PR DESCRIPTION
**Pull request by reldredge71**
Allow option to add a premium to a user's checkout order.

### CODE REVIEW

**Comment by wrandall22** [comment]
Something seems very divergent between your local `master` and the `master` on GitHub.

**Comment by wrandall22** [comment]
Actually, it might be because you created this feature branch from `staging` instead of from `master`?

**Comment by reldredge71** [comment]
Yeah I think I branched off of `staging`.  I can probably rebase this branch right?

**Comment by wrandall22** [comment]
Maybe. You might have to create a new branch from `master` and cherry-pick your commits.

**Pull request closed without merging**
