### PR TITLE
EP-2392 - Upgrade cru-payments

### PR DESCRIPTION
**Pull request by wrandall22**
Update to the cru-payments with security vulnerabilities patched. This required some changes to how imports and mocking happened.

[Jira](https://jira.cru.org/browse/EP-2392)

### CODE REVIEW

**Comment by wrandall22** [comment]
I'll squash whenever we get the full version deployed.

**Review by canac — APPROVED** [review]
Are we going to release a real `1.2.3` version before this merges?

**Comment by wrandall22** [comment]
I believe so, yes.

**Review by dr-bizz — COMMENTED** [review]
We'll publish a prod version of `@cruglobal/cru-payments` before we merge.

**Comment by wrandall22** [comment]
Seems to test well in staging.

**Comment by wrandall22** [comment]
Looks like we need to do some rebasing/squashing.

**Comment by dr-bizz** [comment]
Yeah, I can do it. I don't understand why it does this when merging, and it knows we're merging into the branch which has all these changes already.

**Comment by wrandall22** [comment]
I'm a bit curious about all the stuff removed from `yarn.lock`. Do we know why those are gone?

**Comment by dr-bizz** [comment]
I haven't gone through all of them, but I see many of the packages removed from the `yarn.lock` file are packages I removed or updated on the latest `cru-payments` version.

For example:
`@types/es6-promise`  - Removed from cru-payments
`@types/whatwg-fetch`  - Removed from cru-payments

On the cru-payments yarn.lock file, there were over `8,000` changes, so I would assume the `400` changes we have on this branch are from the initial changes on cru-payments.

**Comment by wrandall22** [comment]
We can merge it one more time to `staging` and test a CC there, then I think we can merge this.

**Comment by dr-bizz** [comment]
It's merged already and I'm testing it now. Might be worth both of us testing to ensure everything is good.

**Comment by dr-bizz** [comment]
- [ ] Deleted a CC
- [ ] Added a CC on the profile.
- [ ] Tested validation tests.
- [ ] Purchased a gift

**Pull request merged**
