### PR TITLE
Refactor country and region api requests into a geographies service

### PR DESCRIPTION
**Pull request by OzzieOrca**
@adammeyer let me know what you think since you originally wrote this. I made it so you just pass the region function a country and it figures out the link internally.

### CODE REVIEW

**Comment by OzzieOrca** [comment]
Also should Canada be using the international address format? I noticed it has regions. Idk how different addresses are there. That doesn't affect this PR either way.

**Comment by adammeyer** [comment]
:+1 Looks good.  Just to confirm, fixtures are only used for testing, correct?

**Comment by adammeyer** [comment]
I originally had it showing the regions dropdown for any country with regions, but that got shot down by QA.  So now it's just US.

**Comment by OzzieOrca** [comment]
Ya they're imported in the `.spec` files only. Interesting... ok

**Pull request merged**
