### PR TITLE
[EP-2470] Enable DD APM Tracing

### PR DESCRIPTION
**Pull request by mattdrees**
[Jira](https://jira.cru.org/browse/EP-2470)

This configures the DD RUM component to send tracing headers in all requests sent to the api url
(cortex gateway). This should let us correlate front-end behavior with back-end traces/errors/logs.

### CODE REVIEW

**Comment by mattdrees** [comment]
@dr-bizz would you be up for helping me figure out the right way to get the 'apiUrl' param at config time? I made a guess here, but the unit tests don't like it and I think it's likely that it would break at runtime as well.

**Comment by dr-bizz** [comment]
> @dr-bizz would you be up for helping me figure out the right way to get the 'apiUrl' param at config time? I made a guess here, but the unit tests don't like it and I think it's likely that it would break at runtime as well.

What you've done is correct, let me take a look at the tests.

**Comment by mattdrees** [comment]
thanks @dr-bizz !

**Review by wrandall22 — APPROVED** [review]

**Comment by mattdrees** [comment]
I'll merge (which I believe auto-deploys to prod) in the morning

**Comment by dr-bizz** [comment]
Yes, merging does auto deploy it to production

**Comment by wrandall22** [comment]
Pushing to `staging` now so it can be tested there.

**Comment by wrandall22** [comment]
Perhaps [this](https://app.datadoghq.com/rum/sessions?query=%40type%3Asession%20%40application.id%3A3937053e-386b-4b5b-ab4a-c83217d2f953%20env%3Astaging&cols=&event=AgAAAYvTeiJimqPhmgAAAAAAAAAYAAAAAEFZdlRlaUppQUFBQ1VpXzU4OFc2czlFTAAAACQAAAAAMDE4YmQzN2ItMTk4ZS00ZTRjLTgyN2UtZjRhY2M3YzI4NmRh&graphType=flamegraph&p_tab=traces&shouldShowLegend=true&sort=time&spanID=4669103394318914244&view=spans&from_ts=1700056562833&to_ts=1700060162833&live=true) shows traces like we mean to see them?

**Comment by mattdrees** [comment]
Yep, that's what I was hoping to see!

**Comment by wrandall22** [comment]
I wish errors like [this one](https://app.datadoghq.com/rum/sessions?query=%40type%3Asession%20%40application.id%3A3937053e-386b-4b5b-ab4a-c83217d2f953%20timeline%3A%5B%7C%40view.name%3A%22%2Fcheckout.html%22%7C%5D%20-timeline%3A%5B%7C%40view.name%3A%22%2Fcheckout.html%22%20%40view.name%3A%22%2Fthank-you.html%22%7C%5D%20%40session.type%3Auser&cols=&event=AgAAAYvVpNcJd7ASrQAAAAAAAAAYAAAAAEFZdlZwT3drQUFCNGtOZWtaVUxOMEFBRAAAACQAAAAAMDE4YmQ2NDktMWY5Yi00MWRiLTk4NTYtNzljMzA5OWI2YWIy&refresh_mode=sliding&viz=stream&from_ts=1700074923229&to_ts=1700161323229&live=true) had traces on them. I wonder why they don't.

**Comment by mattdrees** [comment]
Right.

I don't understand, though, why that error doesn't show up in the Errors [page](https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A3937053e-386b-4b5b-ab4a-c83217d2f953&refresh_mode=sliding&from_ts=1700079937117&to_ts=1700166337117&live=true).

**Pull request merged**
