### PR TITLE
use start date from BE for cart

### PR DESCRIPTION
**Pull request by adammeyer**
if next-draw-date is in past, use current date (mainly for use on stage)

### CODE REVIEW

**Comment by adammeyer** [comment]
@OzzieOrca Wasn't sure why the BE start date wasn't being used.  Is it alright to use it?

**Comment by adammeyer** [comment]
@wrandall22 @mattdrees Can you answer that question?

**Comment by wrandall22** [comment]
It looks like it gets calculated each time the line item is requested. However, it does not take next draw date into account until the asynchronous submission.

**Comment by OzzieOrca** [comment]
Does it take the current date into account? Just curious how it's calculated. Does it use a cached next draw date?

**Comment by wrandall22** [comment]
It looks at current date, doesn't think about next draw date at all. Basically:
````
LocalDate tentativeStartDate = today.withMonth(chosenMonth).withDay(chosenDay);
if (tentativeStartDate.before(today)) {
    return tenativeStartDate.plusYears(1);
}
return tentativeStartDate;
````

**Comment by adammeyer** [comment]
@wrandall22 So when the gift is submitted (completed checkout), that's when next draw date is checked?

**Comment by wrandall22** [comment]
Right.

**Comment by adammeyer** [comment]
@wrandall22 @OzzieOrca I'm fine with using the EP date.  Any objections?

**Comment by wrandall22** [comment]
It will be inaccurate at times; could confuse the donor if they bother to remember what the page said.

**Comment by wrandall22** [comment]
We could try to use the next draw date, but it will make the checkout process a tiny bit slower.

**Comment by OzzieOrca** [comment]
I think that's fine. Maybe I'm thinking to much about corner cases but my last question is how does the next draw date handle weekends? Does it jump forward a couple days?

**Comment by wrandall22** [comment]
Next draw date being not what the donor might expect is not really an edge case, it's probably very frequent.  However, we just use what Siebel gives us for the next draw date. Not sure how Siebel handles weekends, but it's a pretty sturdy process.

**Comment by adammeyer** [comment]
@wrandall22 If a gift is added with a start date of August 28 and the user comes back to their cart tomorrow, would it show August 28, 2018?

**Comment by wrandall22** [comment]
@adammeyer Yes, it looks like it would.

**Comment by adammeyer** [comment]
okay, I'll go ahead and have the FE calculate the date

**Pull request merged**
